version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: adpm
      POSTGRES_PASSWORD: adpm_pass
      POSTGRES_DB: adpm_db
    ports:
      - "5432:5432"
    volumes:
      - data_volume:/var/lib/postgresql/data
volumes:
  data_volume: 